name: mad_test_work
description: "Test work for the Effective Mobile"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  bloc_concurrency: 0.2.5
  dio: 5.4.0
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_svg: 2.0.10+1
  freezed_annotation: 2.4.1
  json_annotation: 4.9.0
  logging: 1.2.0
  provider: 6.1.2
  retrofit: 4.0.3
  shimmer: 3.0.0
  test: 1.24.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: 2.5.2
  build_runner: 2.4.9
  json_serializable: 6.8.0
  mockito: 5.4.4
  surf_lint_rules: 3.0.0
  retrofit_generator: 8.0.6

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/svg/
